---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- make init-venv
- make build-travis
- make init-db

script:
- make vars
- make codecov
- make fast-test

after_success:
- docker-compose -f docker-compose-dev.yml exec web codecov --commit=$TRAVIS_COMMIT

matrix:
  fast_finish: true
