---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- make init-venv
- make reset

script:
- make vars
# FIXME launch coverage tests once fixed
# - make coverage

# after_success:
# - coveralls

matrix:
  fast_finish: true
