language: python

services:
  - postgresql

python:
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - make init-db

install:
  - "pip install -r ./requirements.txt"

script:
  - ./infoscience_exports/manage.py test infoscience_exports


after_success:
  - coveralls


notifications:
  email: false

matrix:
  fast_finish: true
