---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- make init-venv
- make reset

script:
- make vars

# after_success:
# - coveralls

notifications:
  email: false

matrix:
  fast_finish: true
