---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- make init-venv
- make build-travis
- make init-db

script:
- make vars
- make codecov
- make fast-test

after_success:
- ci_env=`bash <(curl -s https://codecov.io/env)`
- docker-compose -f docker-compose-dev.yml exec web bash -c 'bash <(curl -s https://codecov.io/bash)'

matrix:
  fast_finish: true
