---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- make init-venv
- make build-travis
- make init-db

script:
- make vars
- make fast-test
# see https://docs.codecov.io/docs/testing-with-docker for documentation
- ci_env=`bash <(curl -s https://codecov.io/env)`
- docker-compose -f docker-compose-dev.yml run $ci_env web bash -c 'bash <(curl -s https://codecov.io/bash)'

matrix:
  fast_finish: true
