---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
# see https://docs.codecov.io/docs/testing-with-docker for documentation
- ci_env=`bash <(curl -s https://codecov.io/env)`
- make init-venv
- make build-travis
# give time to the DB to be ready
- sleep 2
- make init-db

script:
- docker-compose -f docker-compose-dev.yml exec web make test-travis

matrix:
  fast_finish: true
