web:
  build: .
  restart: always
  expose:
    # used by nginx: see proxy in sites-enabled
    - "${DEV_PORT}"
  links:
    - postgres
  volumes:
    - ./infoscience_exports:/usr/src/app/infoscience_exports
    - ./staticfiles:/usr/src/app/staticfiles
  env_file:
    - .env
  environment:
    # explicitely sets the useful env vars
    - SECRET_KEY=${SECRET_KEY}
    - SITE_URL=${SITE_URL}
    - DATABASE_URL=${DATABASE_URL}
    - MOCKS_DATABASE_URL=${MOCKS_DATABASE_URL}
    # apply settings specific for development
    - DJANGO_SETTINGS_MODULE=settings.dev
  command: gunicorn --reload -w 4 -b :${DEV_PORT} --chdir /usr/src/app/infoscience_exports wsgi:application

nginx:
  build: ./nginx
  ports:
    # out:in = from [out] host, into [in] container 
    - "${DEV_PORT}:${DEV_PORT}"
  volumes:
    - ./nginx/sites-enabled/web.template:/etc/nginx/conf.d/web.template
    - ./nginx/assets:/usr/share/nginx/html
  volumes_from:
    - web
  links:
    # used in nginx/sites-enabled/web.conf
    - web
  environment:
    - DEV_PORT=${DEV_PORT}
    - DOLLAR=$$
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/web.conf && nginx -g 'daemon off;'" 

postgres:
  image: postgres:10
  volumes:
    - /var/lib/postgresql
  ports:
    - "25432:5432"
