web:
  image: epflidevelop/infoscience-exports
  restart: always
  expose:
    - "80"
  links:
    - postgres
  env_file:
    - ./env/django.env
  environment:
    # explicitely sets the useful env vars
    - SECRET_KEY=${SECRET_KEY}
    - SITE_URL=${SITE_URL}
    - DATABASE_URL=${DATABASE_URL}
    - MOCKS_DATABASE_URL=${MOCKS_DATABASE_URL}
    # apply settings specific for production
    - DJANGO_SETTINGS_MODULE=settings.prod
  command: gunicorn --reload -w 4 -b :80 --chdir /usr/src/app/infoscience_exports wsgi:application

postgres:
  image: postgres:10
