web:
  image: epflidevelop/infoscience-exports
  restart: always
  expose:
    - "80"
  links:
    - postgres
  env_file:
    - ./env/django.env
  environment:
    - DJANGO_SETTINGS_MODULE=settings.prod
  command: gunicorn --reload -w 4 -b :80 --chdir /usr/src/app/infoscience_exports wsgi:application

postgres:
  image: postgres:10
  volumes:
    - pgdata:/var/lib/postgresql
  ports:
    - "25432:5432"
